spring.application.name=myshop

server.port=8080
spring.datasource.url=jdbc:mysql://localhost:${MYSQL_PORT:3309}/${MYSQL_DATABASE:my_mysql_db}
spring.datasource.username=${MYSQL_USER:user}
spring.datasource.password=${MYSQL_PASSWORD:password123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true